name: flutter_video_uploader
description: A Flutter app that automatically uploads video files in the background
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.5.0

  # File operations
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  path: ^1.9.1

  # Date formatting and internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # Permissions
  permission_handler: ^12.0.1

  # Background tasks
  workmanager: ^0.9.0+3

  # Notifications
  flutter_local_notifications: ^19.4.2

  # UI components
  flutter_slidable: ^4.0.3

  # JSON serialization
  json_annotation: ^4.8.1
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
